### ISSUE TITLE
`usr/bin/script` command fails on Mac OS X because of Linux-specific parameters

### ISSUE THREAD

**Issue by tobbi** [FlorentRevest/vscode-git-send-email#1]
https://github.com/FlorentRevest/vscode-git-send-email/blob/16deb56ae6b581cc4051d94672a7959b6c84f1b2/src/extension.ts#L223-L226

If you take a look at the Linux manpage for `script`, it's this: https://man7.org/linux/man-pages/man1/script.1.html
However, Mac is based on FreeBSD and the parameters are somewhat different: https://man.freebsd.org/cgi/man.cgi?script(1)

Looks like instead of `-f`, you might want `-F` for FreeBSD-based systems.

**Comment by FlorentRevest** [comment]
Thank you!
